#
# Makefile for rayshade distribution
# C. Kolb 1/91
#
# $Id: Makefile.vc,v 1.1.1.1 2005/01/07 20:51:06 laneb Exp $
#

MAKE = nmake -nologo -f Makefile.vc
STUFF = libray libshade rayshade raypaint

default:
	for %i in ($(STUFF)) do \
		cd %i && (($(MAKE) && cd ..) || cd ..)

#
# Have to keep clean/depend separete so
# Configure will work
#

clean:
	for %i in ($(STUFF)) do \
		cd %i && (($(MAKE) clean && cd ..) || cd ..)
