panel name: L-system
background: 520
size: 170 270

type: SLIDER
name: Derivations
colors: 521 522
origin: 20 200
min/max: 0 10
value: 5
message: d STEPS %d 1

type: SLIDER
name: P1
colors: 521 525
origin: 20 135
min/max: 0 100
value: 33
message: d P1 %d 1

type: SLIDER
name: P2
colors: 521 525
origin: 20 80
min/max: 0 100
value: 33
message: d P2 %d 1

type: SLIDER
name: P3
colors: 521 525
origin: 20 25
min/max: 0 100
value: 33
message: d P3 %d 1

