//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Lstudio.rc
//
#define IDR_DEFAULT                     101
#define IDR_PROJECT                     102
#define IDR_ACCELERATOR1                103
#define IDI_LSTUDIO                     104
#define IDI_PROJECT                     105
#define IDD_ABOUT                       106
#define IDD_COLORMAP                    109
#define IDR_CONTEXTMENUS                110
#define IDD_MATERIAL                    115
#define IDR_TOOLBAR1                    120
#define IDD_LSYSTEM                     122
#define IDB_DINO                        123
#define IDD_SURFACE                     126
#define IDC_GRAB                        131
#define IDD_CONTOUR                     132
#define IDI_AXIS                        138
#define IDI_ADDPOINT                    139
#define IDI_DELETEPOINT                 140
#define IDI_CURVE                       142
#define IDI_POINTS                      143
#define IDI_SEGMENTS                    144
#define IDI_DOWN                        145
#define IDI_UP                          146
#define IDI_RIGHT                       147
#define IDI_LEFT                        148
#define IDI_MOVEPOINT                   150
#define IDC_ADDPOINT                    151
#define IDC_DELETEPOINT                 152
#define IDI_GALLERY                     153
#define IDI_DELETE                      154
#define IDI_CONNECT                     155
#define IDD_VIEWDUMMY                   157
#define IDD_ANYTEXT                     159
#define IDD_ANIMEDIT                    161
#define IDR_HIDDEN                      162
#define IDD_NEWVERSION                  163
#define IDC_CONNECTRIGHT                165
#define IDC_CONNECTLEFT                 166
#define IDC_CONNECTBOTTOM               167
#define IDC_CONNECTTOP                  168
#define IDC_CONNECTRB                   169
#define IDC_CONNECTRT                   170
#define IDC_CONNECTLB                   171
#define IDC_CONNECTLT                   172
#define IDI_PATCH                       174
#define IDI_CONTROLPOINTS               175
#define IDI_CONNECTH                    177
#define IDI_CONNECTV                    178
#define IDI_CONNECTLTRB                 179
#define IDI_CONNECTLBRT                 180
#define IDI_DISCONNECT                  181
#define IDI_ADD                         182
#define IDI_MOVE                        183
#define IDI_RESIZE                      184
#define IDI_ROTATE                      185
#define IDI_TRANSLATE                   186
#define IDI_ZOOM                        187
#define IDI_SELECT                      189
#define IDD_FUNCEDIT                    191
#define IDI_GRID                        192
#define IDI_LABELS                      193
#define IDD_OPTIONS                     194
#define IDD_PANELS                      195
#define IDI_SLIDER                      196
#define IDD_EVALVER                     198
#define IDI_BUTTON                      200
#define IDI_LABEL                       201
#define IDC_ADDSLIDER                   202
#define IDI_CRV_POINTER                 203
#define IDI_GROUP                       204
#define IDD_SLIDERPROP                  205
#define IDI_CRV_ROTATE                  205
#define IDC_DRAG                        206
#define IDD_BUTTONPANELPROP             206
#define IDI_CRV_SCALE                   206
#define IDC_ADDBUTTON                   207
#define IDI_CRV_TRANSLATE               207
#define IDC_ADDLABEL                    208
#define IDI_CRV_AXES                    208
#define IDI_ALIGNLEFT                   209
#define IDI_ALIGNTOP                    210
#define IDI_ALIGNBOTTOM                 211
#define IDI_ALIGNRIGHT                  212
#define IDI_SAMEWIDTH                   213
#define IDI_SAMEHEIGHT                  214
#define IDI_DISTRIBUTEVRT               215
#define IDI_DISTRIBUTEHRZ               216
#define IDI_CRV_ADD_SUCC                217
#define IDI_CRV_DEL_POINT               218
#define IDI_DUPLDOWN                    219
#define IDI_DUPLRIGHT                   220
#define IDD_CRV_TURTLE                  220
#define IDI_PANEL                       221
#define IDD_CRV_TRANSFORM               221
#define IDC_ADDGROUP                    222
#define IDI_CRV_GRIDYZ                  222
#define IDD_LABELPROP                   223
#define IDI_CRV_INIT_BZSURFACE          223
#define IDD_GROUPPROP                   224
#define IDI_CENTERHORZ                  224
#define IDD_DESCRIPTION                 225
#define IDI_CRV_INIT_FIT                225
#define IDI_CENTERVERT                  226
#define IDD_CURVES                      226
#define IDI_CRV_ADD_NE                  227
#define IDD_CRV_CAGD                    227
#define IDI_CRV_ADD_E                   228
#define IDI_CRV_ADD_SE                  229
#define IDD_SAVECHANGES                 229
#define IDI_CRV_ADD_S                   230
#define IDD_FIND                        230
#define IDI_CRV_ADD_SW                  231
#define IDB_LSYSTEM                     231
#define IDI_CRV_ADD_W                   232
#define IDB_VIEW                        232
#define IDI_CRV_ADD_NW                  233
#define IDB_ANIM                        233
#define IDI_CRV_DEL_SURFACE             234
#define IDB_COLORS                      234
#define IDI_CRV_SELECT_ALL              235
#define IDB_SURFACE                     235
#define IDI_CRV_SELECT_CURVE            236
#define IDB_CONTOUR                     236
#define IDI_CRV_SELECT_POINT            237
#define IDB_FUNCTION                    237
#define IDI_CRV_ALIGN                   238
#define IDB_PANEL                       238
#define IDI_CRV_TYPE_BSPLINE            239
#define IDB_DESCRIPTION                 239
#define IDI_CRV_TYPE_BENDPOINT          240
#define IDB_TEXTFILE                    240
#define IDI_CRV_TYPE_BPHANTOM           241
#define IDB_ANIMMASK                    241
#define IDI_CRV_TYPE_BZSPLINE           242
#define IDB_COLORSMASK                  242
#define IDI_CRV_TYPE_BZSURFACE          243
#define IDB_CONTOURMASK                 243
#define IDI_CRV_VAR_BSPLINE             244
#define IDB_DESCRIPTIONMASK             244
#define IDI_CRV_VAR_BZSURFACE           245
#define IDB_FUNCTIONMASK                245
#define IDI_CRV_VAR_DEL                 246
#define IDB_LSYSTEMMASK                 246
#define IDI_CRV_ISURFACE                247
#define IDB_PANELMASK                   247
#define IDI_CRV_MULT                    248
#define IDB_SURFACEMASK                 248
#define IDI_CRV_INSERT                  249
#define IDB_TEXTFILEMASK                249
#define IDI_CRV_DELETE                  250
#define IDB_VIEWMASK                    250
#define IDI_CRV_TYPE                    251
#define IDD_VIEWOPTIONS                 251
#define IDI_CRV_SELECT                  252
#define IDD_INPUTFUNCPOINT              252
#define IDI_CRV_VARIATION               253
#define IDD_WAITFORCPFGTOUPDATE         253
#define IDD_WAITFORSEMAPHORE            253
#define IDI_CRV_UNDO                    254
#define IDI_CRV_TYPE_BCLOSED            255
#define IDD_CHOOSETXTFMT                255
#define IDI_CRV_TURTLE                  256
#define IDI_CRV_TRANSFORM               257
#define IDI_CRV_SAVE                    258
#define IDI_CRV_REDO                    259
#define IDI_CRV_OPEN                    260
#define IDI_CRV_INIT_VIEW               261
#define IDI_CRV_INIT_BSPLINE            262
#define IDC_PAN                         262
#define IDI_CRV_GRIDXZ                  263
#define IDI_CRV_GRIDXY                  264
#define IDI_CRV_GRID                    265
#define IDI_CRV_DPOINTS                 266
#define IDI_CRV_DCURVE                  267
#define IDI_CRV_DCONVEX                 268
#define IDI_CRV_ADD_PRED                269
#define IDI_CRV_ADD_N                   270
#define IDI_CRV_DIVIDE                  271
#define IDI_CRV_SHOW                    272
#define IDI_CRV_HIDE                    273
#define IDI_CRV_BRIGHT                  274
#define IDI_CRV_DARK                    275
#define IDI_CRV_SPAPER                  276
#define IDI_CRV_FLIP                    277
#define IDI_CRV_CAGD                    278
#define IDI_FINDNEXT                    279
#define IDI_FINDPREV                    280
#define IDI_SAVEAS                      281
#define IDI_CLOSE                       282
#define IDD_SETLPFGPATH                 283
#define IDR_CREDITS                     285
#define IDC_CRSS                        286
#define IDD_CLRMAPOPTIONS               287
#define IDI_BROWSER                     288
#define IDD_CONNECTBROWSER              290
#define IDI_VLBOBJ                      291
#define IDI_VLBEXT                      292
#define IDI_ICON1                       293
#define IDD_LOCREM                      298
#define IDC_SOURCE                      299
#define IDC_TARGET                      300
#define IDI_ICON2                       301
#define IDB_BITMAP2                     303
#define IDB_BITMAP3                     304
#define ID_SNAPICON_SNAPNOW             307
#define IDS_EMPTY                       307
#define ID_SNAPICON_CLOSE               309
#define IDC_SNAP                        310
#define IDD_NEWBROWSER                  313
#define IDD_BROWSER_LOCAL               343
#define IDI_ALIGNLEFTA                  344
#define IDI_ALIGNBOTTOMA                345
#define IDI_ICON3                       346
#define IDC_SETPNT                      347
#define IDD_INPUTCNTRPOINT              348
#define ID_OBJECT_SAVEAS                349
#define ID_OBJECT_WRITETOLABTABLE       350
#define ID_OBJECT_READFROMLABTABLE      351
#define ID_OBJECT_LABTABLESHELL         352
#define IDD_TRANSFEROBJS                356
#define IDD_OPTIONSNEW                  358
#define IDD_FINDOBJECT                  359
#define IDR_SIMULATORMENU               360
#define IDS_PROGRAMCAPTION              1000
#define IDS_NEWPROJECTTITLE             1001
#define IDC_REDSLIDER                   1002
#define IDS_NEWLSYSTEM                  1002
#define IDS_VCGENERAL                   1003
#define IDC_GREENSLIDER                 1003
#define IDC_BLUESLIDER                  1004
#define IDS_VCPROJECTION                1004
#define IDC_COLORMAP                    1005
#define IDS_VCTURTLEPARAMS              1005
#define IDS_FILE                        1006
#define IDS_STATUS                      1007
#define IDC_ADD                         1008
#define IDC_REMOVE                      1009
#define IDS_DELETED                     1010
#define IDS_ADDED                       1011
#define IDC_NAME                        1012
#define IDS_MODIFIED                    1012
#define IDS_BROWSEFORLPFGPATH           1013
#define IDS_HIDE_EXTENSIONS             1014
#define IDS_HIDE_ICON                   1015
#define IDS_SHOW_EXTENSIONS             1016
#define IDS_SHOW_ICON                   1017
#define IDS_NEWMODEL                    1018
#define IDC_MATPREVIEW                  1019
#define IDS_NEWVIEW                     1019
#define IDS_NOTHING                     1020
#define IDC_AMBIENT                     1025
#define IDC_DIFFUSE                     1026
#define IDC_SPECULAR                    1027
#define IDC_EMISSION                    1028
#define IDC_GALLERY                     1029
#define IDC_LSYSTEM                     1058
#define IDC_SHININESS                   1059
#define IDC_TRANSPARENCY                1060
#define IDC_CP1                         1069
#define IDC_CP2                         1070
#define IDC_CP3                         1071
#define IDC_CP4                         1072
#define IDC_CP5                         1073
#define IDC_CP6                         1074
#define IDC_CP7                         1075
#define IDC_CP8                         1076
#define IDC_CP9                         1077
#define IDC_CP10                        1078
#define IDC_CP11                        1079
#define IDC_CP12                        1080
#define IDC_CP13                        1081
#define IDC_CP14                        1082
#define IDC_CP15                        1083
#define IDC_CP16                        1084
#define IDC_PLACEMENT                   1085
#define IDC_XTHUMB                      1086
#define IDC_YTHUMB                      1087
#define IDC_ZTHUMB                      1088
#define IDC_CREDITS                     1096
#define IDC_SWAPINTERVAL                1096
#define IDC_GOTO                        1096
#define IDC_MESSAGE                     1096
#define IDC_FILENAME                    1096
#define IDC_FIND                        1096
#define IDC_SAMPLES                     1096
#define IDC_XVAL                        1096
#define IDC_OOFS                        1096
#define IDC_LPFGPATH                    1096
#define IDC_VIEW                        1097
#define IDC_YVAL                        1097
#define IDC_FINDTXT                     1097
#define IDC_CLOSED                      1099
#define IDC_POINTS                      1103
#define IDC_SEGMENTS                    1104
#define IDC_CURVE                       1105
#define IDC_AXIS                        1106
#define IDC_MOVE                        1109
#define IDC_DELETE                      1110
#define IDC_MATERIALS                   1118
#define IDC_OPEN                        1120
#define IDC_SAVE                        1121
#define IDC_SAVEAS                      1122
#define IDC_DOUBLEBUFFER                1122
#define IDC_CRV_POINTER                 1122
#define IDC_CLEARBF                     1123
#define IDC_CRV_ROTATE                  1123
#define IDC_SCALEBF                     1124
#define IDC_CRV_SCALE                   1124
#define IDC_NEWVIEWBF                   1125
#define IDC_CRV_TRANSLATE               1125
#define IDC_FIRSTFRAME                  1126
#define IDC_CRV_AXES                    1126
#define IDC_LASTFRAME                   1127
#define IDC_CRV_GRID                    1127
#define IDC_LASTDEFAULT                 1128
#define IDC_CRV_DPOINTS                 1128
#define IDC_LASTSPECIFIED               1129
#define IDC_CRV_DCONVEX                 1129
#define IDC_STEP                        1130
#define IDC_CRV_DCURVE                  1130
#define IDC_FRAMEINTERVALS              1131
#define IDC_CRV_TYPE                    1131
#define IDC_EDIT                        1132
#define IDC_GRIDPREVIEW                 1132
#define IDC_HCENTERBF                   1132
#define IDC_CRV_INIT_VIEW               1135
#define IDC_CRV_UNDO                    1136
#define IDC_CRV_REDO                    1137
#define IDC_GRID                        1139
#define IDC_MATCHCASE                   1139
#define IDC_SLIDER                      1140
#define IDC_OUTLINE                     1140
#define IDC_GO                          1140
#define IDC_COLOR                       1140
#define IDC_ADVANCED                    1140
#define IDC_GLOBAL                      1140
#define IDC_BROWSE                      1140
#define IDC_CLOSE                       1141
#define IDC_BUTTON                      1141
#define IDC_FILL                        1141
#define IDC_GROUP                       1142
#define IDC_TRANSLATE                   1143
#define IDC_LABEL                       1143
#define IDC_ZOOM                        1144
#define IDC_ALIGNLEFT                   1144
#define IDC_SELECT                      1145
#define IDC_FNAME                       1146
#define IDC_ALIGNRIGHT                  1146
#define IDC_OBJID                       1147
#define IDC_ALIGNTOP                    1147
#define IDC_ALIGNBOTTOM                 1148
#define IDC_LABELS                      1149
#define IDS_ALIGNHORZ                   1149
#define IDS_ALIGNVERT                   1150
#define IDC_CRV_INIT_BSPLINE            1150
#define IDC_DISTRIBUTEHRZ               1151
#define IDC_CRV_INIT_BZSURFACE          1151
#define IDC_DISTRIBUTEVRT               1152
#define IDC_DISTRIBUTEVERT              1152
#define IDC_CRV_INIT_FIT                1152
#define IDS_LABELSTT                    1153
#define IDC_MATNO                       1154
#define IDC_CRV_INSERT                  1154
#define IDS_SAVENEWPROJECT              1154
#define IDC_TRANSPLBL                   1155
#define IDC_CRV_DELETE                  1155
#define IDS_OPEN                        1155
#define IDC_SHINLBL                     1156
#define IDS_SAVE                        1156
#define IDC_EMISSLBL                    1157
#define IDS_SAVEAS                      1157
#define IDC_SPECLBL                     1158
#define IDS_CLOSE                       1158
#define IDC_DIFFLBL                     1159
#define IDS_FINDPREV                    1159
#define IDC_AMBLBL                      1160
#define IDS_FINDNEXT                    1160
#define IDS_BROWSENEWVERDIR             1161
#define IDC_CTPT                        1162
#define IDS_OVERWRITEPROJECT            1162
#define IDC_NMLBL                       1163
#define IDS_BROWSEOOFS                  1163
#define IDC_TEXT                        1165
#define IDC_CRV_ALIGN                   1165
#define IDC_STATUS                      1166
#define IDC_CRV_SELECT                  1166
#define IDC_CRV_OPEN                    1167
#define IDC_CRV_SAVE                    1168
#define IDC_MIN                         1169
#define IDC_CRV_STATUS                  1169
#define IDC_MAX                         1170
#define IDC_VALUE                       1171
#define IDC_DEFSTATE                    1172
#define IDC_DUPLDOWN                    1173
#define IDC_DUPLRIGHT                   1174
#define IDC_NAMELBL                     1175
#define IDS_DELETEFROMGALLERY           1175
#define IDC_CRV_MULT                    1177
#define IDC_ALIGNLBL                    1178
#define IDC_DISPLBL                     1179
#define IDC_CRV_TURTLE                  1179
#define IDC_EDITLBL                     1180
#define IDC_CRV_TRANSFORM               1180
#define IDC_CRV_TURTLE_CX               1180
#define IDC_CRV_TRANSFORM_RA            1181
#define IDC_CRV_DIVIDE                  1181
#define IDC_VIEWFILE                    1182
#define IDC_CRV_TURTLE_CY               1182
#define IDC_CRV_TRANSFORM_RX            1182
#define IDC_CRV_SHOW                    1182
#define IDC_FILE                        1183
#define IDC_CRV_TURTLE_CZ               1183
#define IDC_CRV_TRANSFORM_RY            1183
#define IDC_CRV_HIDE                    1183
#define IDC_ACTIONLBL                   1184
#define IDC_CRV_TURTLE_EX               1184
#define IDC_CRV_TRANSFORM_RZ            1184
#define IDC_CRV_BRIGHT                  1184
#define IDC_ASSOCLBL                    1185
#define IDC_CRV_TURTLE_EY               1185
#define IDC_CRV_TRANSFORM_SX            1185
#define IDC_CRV_DARK                    1185
#define IDC_BROWSEFILE                  1186
#define IDC_CRV_TURTLE_EZ               1186
#define IDC_CRV_TRANSFORM_SY            1186
#define IDC_CRV_SPAPER                  1186
#define IDC_CRV_TURTLE_HX               1187
#define IDC_CRV_TRANSFORM_SZ            1187
#define IDC_CRV_FLIP                    1187
#define IDC_CRV_TURTLE_HY               1188
#define IDC_CRV_TRANSFORM_TX            1188
#define IDC_CRV_CAGD                    1188
#define IDC_CRV_TURTLE_HZ               1189
#define IDC_CRV_TRANSFORM_TY            1189
#define IDC_CRV_TURTLE_UX               1190
#define IDC_CRV_TRANSFORM_TZ            1190
#define IDC_CRV_TURTLE_UY               1191
#define IDC_CRV_TRANSFORM_EX            1191
#define IDC_EXECUTE                     1192
#define IDC_CRV_TURTLE_UZ               1192
#define IDB_CRV_TRANSFORM_R             1192
#define IDC_DESIGN                      1193
#define IDC_CRV_TURTLE_S                1193
#define IDC_MODEGRP                     1194
#define IDC_CRV_TRANSFORM_EY            1194
#define IDC_CRV_TRANSFORM_EZ            1195
#define IDB_CRV_TRANSFORM_S             1196
#define IDB_CRV_TRANSFORM_T             1197
#define IDB_CRV_TRANSFORM_E             1198
#define IDC_SIMPLE                      1201
#define IDC_CRV_CAGD_A                  1202
#define IDC_DIFF                        1203
#define IDC_CRV_CAGD_B                  1203
#define ID_FIND                         1204
#define IDC_CRV_CAGD_C                  1204
#define IDC_CRV_CAGD_D                  1205
#define IDC_ICONS                       1206
#define IDC_CRV_CAGD_F                  1206
#define IDC_BOTH                        1207
#define IDC_CRV_CAGD_T                  1207
#define IDC_ITEM                        1208
#define IDC_CRV_CAGD_N                  1208
#define IDC_BACKGROUND                  1211
#define IDC_FLIP                        1212
#define IDC_SMPLSLBL                    1213
#define IDC_MINVAL                      1215
#define IDC_MAXVAL                      1216
#define IDC_WAITING                     1216
#define IDC_FOREGROUND                  1217
#define IDC_WAITING2                    1217
#define IDC_FONT                        1219
#define IDC_FONTSIZE                    1221
#define IDC_SAMPLE                      1222
#define IDC_APPLY                       1223
#define IDC_PERSONAL                    1231
#define IDC_FINDPREV                    1232
#define IDC_FINDNEXT                    1233
#define IDC_WIDTH                       1233
#define IDC_LOCATION                    1234
#define IDC_EDRED                       1240
#define IDC_EDGREEN                     1241
#define IDC_255                         1241
#define IDC_EDBLUE                      1242
#define IDC_1                           1242
#define IDC_DETAILS                     1243
#define IDC_HOST                        1244
#define IDC_USER                        1245
#define IDC_PASSWORD                    1246
#define IDC_SAVEPASSWORD                1247
#define IDD_OPENCONFIG                  1547
#define IDD_SAVEAS                      1548
#define IDS_LSYSTEM                     2100
#define IDS_VIEW                        2101
#define IDS_COLORS                      2102
#define IDS_MATERIALS                   2103
#define IDS_SURFACES                    2104
#define IDS_TEXTURES                    2105
#define IDS_CONTOURS                    2106
#define IDS_SPLINES                     2107
#define IDS_PIXELS                      2108
#define IDS_SHADED                      2109
#define IDS_ANIMATE                     2110
#define IDS_ANYTEXT                     2111
#define IDS_FUNCTIONS                   2112
#define IDS_PANELS                      2113
#define IDS_DESCRIPTION                 2114
#define IDS_LABELCOLOR                  2115
#define IDS_PROGRAM                     2116
#define IDS_PARAMETERS                  2117
#define IDS_BACKGROUND                  2500
#define IDS_GRID                        2501
#define IDS_AXIS                        2502
#define IDS_CURVE                       2503
#define IDS_SEGMENTS                    2504
#define IDS_POINTS                      2505
#define IDS_LABELS                      2506
#define IDS_DETAILSSHOW                 2507
#define IDS_DETAILSHIDE                 2508
#define IDS_VLABBROWSER                 2509
#define IDS_NOTCONNECTED                2510
#define IDS_DISCONNECTFIRST             2511
#define IDS_BROWSELOCREM                2512
#define IDS_BROWSEREMLOC                2513
#define IDC_REMOTE                      2514
#define IDS_DELETEOBJECT                2514
#define IDC_CHANGEIDENTITY              2514
#define IDC_DISPONREQUEST               2514
#define IDS_DELETEOBJECTANDCHILDREN     2515
#define IDS_MAKEEXTENSION               2516
#define IDS_RERUN                       2517
#define IDC_EDITX                       2527
#define IDC_FNDLG                       2529
#define IDC_EDITCOORD                   2531
#define IDC_EDITY                       2532
#define IDC_NUMCONSEC                   2534
#define IDC_STEPNO                      2535
#define IDC_TYPECB                      2536
#define IDC_TYPELBL                     2537
#define IDC_PROGRESS1                   2538
#define IDC_SECRET                      2541
#define IDC_DIFFLIST                    2542
#define IDC_CONFIRMEXIT                 2543
#define IDC_CRLFTRANSLATE               2544
#define IDC_EDIT1                       2545
#define IDC_ICONSIZE                    2546
#define IDC_ICONSIZESPIN                2547
#define IDC_CRLFEDIT                    2548
#define IDC_CRLFADD                     2549
#define IDC_CRLFREMOVE                  2550
#define IDC_MAKE_DEFAULT                2551
#define IDC_TRIGGER                     2552
#define IDC_TRIGGERLBL                  2553
#define IDC_WHOLENAME                   2556
#define IDC_FINDOBJ                     2557
#define IDERR_CREATELSYSEDIT            10000
#define IDERR_CREATEVIEWEDIT            10001
#define IDERR_CREATENEWPROJECT          10002
#define IDERR_CREATESTDOUT              10003
#define IDERR_CREATESPLITTER            10004
#define IDERR_CREATECOLORMAPEDIT        10005
#define IDERR_CREATETEXTUREMANAGER      10006
#define IDERR_NOEMPTYNAMES              10007
#define IDERR_CREATEMATERIALEDIT        10008
#define IDERR_LOADINGPROJECT            10009
#define IDERR_LOADINGINVVER             10010
#define IDERR_CREATECPFGVIEW            10011
#define IDERR_CREATESURFACEEDIT         10012
#define IDERR_CREATECONTOUREDIT         10013
#define IDERR_CANNOTADDTOGALLERY        10014
#define IDERR_CANNOTADDPOINT            10015
#define IDERR_INVALIDFILEHEADER         10016
#define IDERR_LSYSTEMSTAMP              10017
#define IDERR_VIEWSTAMP                 10018
#define IDERR_UNKNOWNVIEWPARAM          10019
#define IDERR_TEXTURESTAMP              10020
#define IDERR_MATERIALSTAMP             10021
#define IDERR_NOMATERIALENDSTAMP        10022
#define IDERR_COLORMAPSTAMP             10023
#define IDERR_NOCOLORMAPENDSTAMP        10024
#define IDERR_READINGCOLORMAP           10025
#define IDERR_INVALIDVALREADINGCOLORMAP 10026
#define IDERR_TOOMANYMATERIALS          10027
#define IDERR_SURFACESTAMP              10028
#define IDERR_NOSURFACEENDSTAMP         10029
#define IDERR_CONTOURSTAMP              10030
#define IDERR_NOCONTOURENDSTAMP         10031
#define IDERR_READINGSURFACE            10032
#define IDERR_ONEPATCHSURFACEONLY       10033
#define IDERR_LOADINGPATCH              10034
#define IDERR_READINGCONTOUR            10035
#define IDERR_ONEINSTANCE               10036
#define IDERR_CPFGWAITTIMEOUT           10037
#define IDERR_CREATEANIMEDIT            10038
#define IDERR_ANIMATESTAMP              10039
#define IDERR_LAUNCHCPFG                10040
#define IDERR_NOCOLORMODEINFO           10041
#define IDERR_TOOMANYMATERIALSIMPORT    10042
#define IDERR_CANNOTCREATETMPDIR        10043
#define IDERR_CREATEANYTEXT             10044
#define IDERR_READINGPATCHCLRINFO       10045
#define IDERR_UNKNOWNANIMLABEL          10046
#define IDERR_LVIEW                     10047
#define IDERR_NEWVERNAMEEMPTY           10048
#define IDERR_CANNOTCREATEDIR           10049
#define IDERR_LAUNCHIE                  10050
#define IDERR_SRCFILE                   10051
#define IDERR_DONTDROPFILES             10052
#define IDERR_CANNOTSAVEFILE            10053
#define IDERR_CREATEFUNCEDIT            10054
#define IDERR_FUNCSTAMP                 10055
#define IDERR_READINGFUNCTION           10056
#define IDERR_CANNOTIMPORTFROMHERE      10057
#define IDERR_INVALIDSHININESS          10058
#define IDERR_NOHTMLHANDLER             10059
#define IDERR_HINST0                    10060
#define IDERR_HINST31                   10061
#define IDERR_HINSTFNF                  10062
#define IDERR_HINSTPNF                  10063
#define IDERR_HINSTBF                   10064
#define IDERR_CPFGERROREXIT             10065
#define IDERR_CREATEPANELS              10066
#define IDYESNO_NOTAPROJECT             10067
#define IDS_EXITLSTUDIO                 10068
#define IDERR_NOPDFHANDLER              10069
#define IDERR_LOADINGPANELS             10070
#define IDERR_PANELFULL                 10071
#define IDERR_MINLTMAX                  10072
#define IDERR_VALOUTOFRANGE             10073
#define IDERR_PANELNAMEEMPTY            10074
#define IDS_EVALVER                     10075
#define IDERR_NOTHINGSELECTEDTODELETE   10076
#define IDERR_NOTHINGSELECTEDTODUPL     10077
#define IDERR_TOOMANYITEMSTODUPL        10078
#define IDERR_TOOMANYITEMSINPANEL       10079
#define IDERR_UNKNOWNPANELCTRLTYPE      10080
#define IDERR_READINGPANELSLIDER        10081
#define IDERR_READINGPANELBUTTON        10082
#define IDERR_READINGPANELLABEL         10083
#define IDERR_READINGPANEL              10084
#define IDS_MESSAGETOOLONG              10085
#define IDERR_PEDCOMMAND                10086
#define IDERR_OPENSRCFILE               10087
#define IDERR_NOBUTTONSINSIDE           10088
#define IDERR_EXECPED                   10089
#define IDERR_LINETOOLONG               10090
#define IDERR_EOFFOUND                  10091
#define IDERR_SRCWRITE                  10092
#define IDERR_EXECPEDCMND               10093
#define IDWRN_PEDNSUSPSCALE             10094
#define IDERR_PEDNINVALIDFIELD          10095
#define IDERR_PEDNFINDFIELD             10096
#define IDERR_PEDNMSCALESMALL           10097
#define IDERR_PEDNMFINDFIELD            10098
#define IDERR_PEDNMINVALIDFIELD         10099
#define IDERR_EOFTEXTFOUND              10100
#define IDERR_WNDLINETOOLONG            10101
#define IDERR_EDLINLINETOOLONG          10102
#define IDERR_PEDOMISSINGCOLON          10103
#define IDERR_PEDNUMFINDFIELD           10104
#define IDERR_PEDNUMINVALIDFIELD        10105
#define IDERR_PNLGRPTOOMANYBUTTONS      10106
#define IDERR_PNLGRPNOBTNS              10107
#define IDERR_READINGPANELGROUP         10108
#define IDERR_PANELGROUPTOOMANYBUTTONS  10109
#define IDS_CLOSEPANELSBEFOREEDIT       10110
#define IDERR_CREATEDESCRIPTION         10111
#define IDERR_CURVESTAMP                10112
#define IDERR_CREATECURVEEDIT           10113
#define IDERR_CANNOTDELETE              10114
#define IDERR_PATTERNNOTFOUND           10115
#define IDERR_RESSHORTCUT               10116
#define IDERR_SRTCTMSNGFILE             10117
#define IDERR_XTOOBIG                   10118
#define IDERR_XTOOSMALL                 10119
#define IDERR_INVVERFORBOUNDFUNCS       10120
#define IDERR_FUNCGALLERY               10121
#define IDERR_FUNCGALLERYVER            10122
#define IDERR_NOACTIVEPROJECT           10123
#define IDERR_NOTHINGTOCUSTOMIZE        10124
#define IDERR_INVVERFORBOUNDCONTOURS    10125
#define IDERR_CONTOURVERSION            10126
#define IDERR_NOTIMPLEMENTEDYET         10127
#define IDERR_READINGCONFIG             10128
#define IDERR_CONTOURGALLERY            10129
#define IDERR_CONTOURGALLERYVER         10130
#define IDERR_UNNAMEDPANELEXECUTE       10131
#define IDERR_LPFGCRASHED               10132
#define IDERR_OUTOFMEMORY               10133
#define IDERR_FILE_NOT_FOUND            10134
#define IDERR_ACCESS_DENIED             10135
#define IDERR_NOASSOC                   10136
#define IDERR_DASHWINCOMPLETE           10137
#define IDERR_DASHWPINCOMPLETE          10138
#define IDERR_DASHWRINCOMPLETE          10139
#define IDERR_DASHWPRINCOMPLETE         10140
#define IDERR_NEWPROJECT                10141
#define IDERR_VLBROWSER                 10142
#define IDERR_HOSTEMPTY                 10143
#define IDERR_USEREMPTY                 10144
#define IDERR_OOFSEMPTY                 10145
#define IDERR_CANNOTRESOLVEHOST         10146
#define IDERR_WINSOCK                   10147
#define IDERR_CREATESOCK                10148
#define IDERR_SOCKETWR                  10149
#define IDERR_SOCKETRD                  10150
#define IDERR_CNCTCLOSED                10151
#define IDERR_CANNOTCONNECT             10152
#define IDERR_CANNOTLOGIN               10153
#define IDERR_VLBGETEXTENSIONS          10154
#define IDERR_VLBGETEXTNOTALL           10155
#define IDERR_NOOBJECTSELECTED          10156
#define IDERR_CONNECTFIRST              10157
#define IDERR_SELECTTARGETFIRST         10158
#define IDERR_NEWEXTNMEMPTY             10159
#define IDERR_COPYPASTENOTSUPPORTED     10160
#define IDERR_FETCHICON                 10161
#define IDERR_OPENRGBREAD               10162
#define IDERR_ONLYRGBFILE               10163
#define IDERR_DELOOFSROOT               10164
#define IDERR_DELTREEREMOTE             10165
#define IDERR_CREATENEWVER              10166
#define IDERR_BROWSERNOTRUNNING         10167
#define IDERR_OPENOBJECT                10168
#define IDERR_READVLBCONFIG             10169
#define IDERR_NEWVERPARENTEMPTY         10170
#define IDERR_CREATEEXTENSION           10171
#define IDERR_PASTESRCNOTSET            10172
#define IDERR_PASTESRCTRGSAME           10173
#define IDERR_PASTINGOBJECTS            10174
#define IDERR_PASTINGACROSSBROWSERS     10175
#define IDERR_LOCATEOBJECT              10176
#define IDERR_CANNOTRENAMEOBJ           10177
#define IDERR_NAMENOTDIR                10178
#define IDERR_PASTEONITSELF             10179
#define IDS_EXPIREDVER                  10180
#define IDS_SPLREGULAR                  10181
#define IDS_SPLENDPTINT                 10182
#define IDERR_WRITECONFIG               10183
#define IDERR_PANELVER                  10184
#define IDS_WAITINGSIMULATOR            10185
#define IDERR_NOTARGETFILE              10186
#define IDERR_INVALIDOOFS               10187
#define IDERR_SIMULATORCRASHED          10188
#define IDERR_SIMULATORCOMMAND          10189
#define IDS_TEXTURESFILTER              11000
#define IDS_TEXTUREALREADYLOADED        11001
#define IDS_1BITMAP                     11002
#define IDS_4BITMAP                     11003
#define IDS_8BITMAP                     11004
#define IDS_24BITMAP                    11005
#define IDS_RENAMETEXTURE               11006
#define IDS_PROJECTFILTER               11007
#define IDS_DELETE                      11008
#define IDS_RESET                       11009
#define IDS_GALLERYFILTER               11010
#define IDS_IMPORTBROWSETITLE           11011
#define IDS_IMPORTTITLE                 11012
#define IDS_CONFIRM                     11013
#define IDS_SAVEBEFORECLOSE             11014
#define IDS_ANYTEXTFILTER               11015
#define IDS_ANYFILEFILTER               11016
#define IDS_BROWSEOBJECT                11017
#define IDS_CUT                         11018
#define IDS_EXPORTBROWSETITLE           11019
#define IDS_SAVEANYTEXT                 11020
#define IDS_SAVEANYTEXTFILE             11021
#define IDS_EVALTEXT                    11022
#define IDS_EXPIRED                     11023
#define IDS_NOPROPERTIESTOSET           11024
#define IDS_PANELITEMNAMETOOLONG        11025
#define IDS_FILEINDIFFDIR               11026
#define IDS_DESIGNMODE                  11027
#define IDS_USEMODE                     11028
#define IDS_CURVEFILTER                 11029
#define IDS_WAITING4CPFG                11030
#define IDS_AMBIENT                     11031
#define IDS_DIFFUSE                     11032
#define IDS_SPECULAR                    11033
#define IDS_EMISSION                    11034
#define IDS_CONFIGFILTER                11035
#define IDS_SELECTOOFSROOT              11036
#define IDS_DEMOFILEFILTER              11037
#define IDS_SAVEDEMOFILE                11038
#define IDERR_SAVINGOBJECT              11039
#define IDERR_BUILDCOMMAND              11040
#define ID_TOOLS_OPTIONS                40076
#define ID_FROMCPFG_ERROREXIT           40077
#define ID_HIDDEN_TESTCPFGVIEW          40079
#define ID_HIDDEN_GOTOLINE              40083
#define IDP_CRV_ISURFACE_ABOVE_LEFT     40083
#define ID_PANELGALLERY_NEW             40084
#define ID_PANELGALLERY_DELETE          40085
#define ID_PANELDESIGN_APPLY            40088
#define ID_PANELDESIGN_RETRIEVEFROMGALLERY 40089
#define ID_PANELDESIGN_ADDASNEW         40090
#define IDP_CRV_IPOINT_PRED             40091
#define ID_PANELGALLERY_EXECUTE         40092
#define ID_PANELGALLERY_EXECUTEALL      40093
#define ID_PANELCNTXT_NEWMODEL          40094
#define ID_PANELCNTXT_NEWLSYSTEM        40095
#define ID_PANELCNTXT_NEWVIEW           40096
#define ID_PANELALIGNHORZ_ALIGNLEFT     40097
#define ID_PANELALIGNHORZ_ALIGNRIGHT    40098
#define ID_PANELALIGNHORZ_CENTER        40099
#define ID_PANELALIGNVERT_ALIGNTOP      40100
#define ID_PANELALIGNVERT_ALIGNBOTTOM   40101
#define ID_PANELALIGNVERT_CENTER        40102
#define ID_PANELCNTXT_CLOSE             40105
#define IDP_CRV_DELETE_VARIATION        40106
#define IDP_CRV_GRID_GRID               40107
#define IDP_CRV_GRID_XY                 40108
#define IDP_CRV_GRID_XZ                 40109
#define IDP_CRV_GRID_YZ                 40110
#define IDP_CRV_TYPE_BSPLINE            40111
#define IDP_CRV_TYPE_BCLOSED            40112
#define IDP_CRV_TYPE_BENDPOINT          40113
#define IDP_CRV_TYPE_BPHANTOM           40114
#define IDP_CRV_TYPE_BZSPLINE           40115
#define IDP_CRV_TYPE_BZSURFACE          40116
#define IDP_CRV_SELECT_ALL              40117
#define IDP_CRV_SELECT_CURVE            40118
#define IDP_CRV_IPOINT_SUCC             40122
#define IDP_CRV_ISURFACE_ABOVE          40123
#define IDP_CRV_ISURFACE_ABOVE_RIGHT    40124
#define IDP_CRV_ISURFACE_LEFT           40125
#define IDP_CRV_ISURFACE_RIGHT          40126
#define IDP_CRV_ISURFACE_BELOW_LEFT     40127
#define IDP_CRV_ISURFACE_BELOW          40128
#define IDP_CRV_ISURFACE_BELOW_RIGHT    40129
#define IDP_CRV_IVARIATION_BSPLINE      40130
#define IDP_CRV_IVARIATION_BZSURFACE    40131
#define IDP_CRV_DELETE_POINT            40132
#define IDP_CRV_DELETE_SURFACE          40133
#define IDP_CRV_MULT_1                  40134
#define IDP_CRV_MULT_2                  40135
#define IDP_CRV_MULT_3                  40136
#define IDP_CRV_MULT_4                  40137
#define IDP_CRV_SHOW_ALL                40138
#define ID_HIDDEN_TESTARCBALL           40140
#define ID_HIDDEN_FIND                  40141
#define ID_PANELCNTXT_RESET             40145
#define ID_PANELCNTXT_RERUN             40146
#define ID_FUNCTIONGALLERY_BIND         40148
#define IDP_CRV_SHOW_CURVE              40149
#define IDP_CRV_SHOW_PATCH              40150
#define IDP_CRV_SHOW_POINT              40151
#define IDP_CRV_HIDE_CURVE              40152
#define IDP_CRV_HIDE_PATCH              40153
#define IDP_CRV_HIDE_POINT              40154
#define IDP_CRV_BRIGHT_ALL              40155
#define IDP_CRV_BRIGHT_CURVE            40156
#define IDP_CRV_BRIGHT_PATCH            40157
#define IDP_CRV_BRIGHT_POINT            40158
#define IDP_CRV_DARK_CURVE              40159
#define IDP_CRV_DARK_PATCH              40160
#define IDP_CRV_DARK_POINT              40161
#define ID_COLORMAPWND_APPLY            40165
#define IDP_CRV_FPATCH_X                40170
#define IDP_CRV_FPATCH_Y                40171
#define IDP_CRV_SPATCH_ALL              40172
#define IDP_CRV_SPATCH_CORNER           40173
#define IDP_CRV_SPATCH_LEFT             40174
#define IDP_CRV_SPATCH_RIGHT            40175
#define IDP_CRV_SPATCH_TOP              40176
#define IDP_CRV_SPATCH_BOTTOM           40177
#define IDP_CRV_CAGD_BLOSSOM            40178
#define IDP_CRV_CAGD_INTERPOLATION      40179
#define ID_HIDDEN_FINDAGAIN             40187
#define ID_HELP_LPFGMANUAL              40190
#define ID_HELP_VVMANUAL                40191
#define ID_SURFACEGALLERY_BIND          40192
#define ID_SURFACEGALLERY_NEWFORMAT     40194
#define ID_HIDDEN_LOADARGV1             40197
#define ID_FUNCTIONGALLERY_CUT          40198
#define ID_CONTOURGALLERY_CUT           40199
#define ID_SURFACEGALLERY_CUT           40200
#define ID_FUNCTIONGALLERY_PASTE_AFTER  40202
#define ID_FUNCTIONGALLERY_PASTE_BEFORE 40203
#define ID_SURFACEGALLERY_PASTE_BEFORE  40204
#define ID_SURFACEGALLERY_PASTE_AFTER   40205
#define ID_CONTOURGALLERY_PASTE_BEFORE  40206
#define ID_CONTOURGALLERY_PASTE_AFTER   40207
#define ID_HIDDEN_OPENVIARASERVER       40210
#define ID_CONTOURGALLERY_BIND          40211
#define ID_HIDDEN_EDITCOMPONENT_LSYSTEM 40212
#define ID_HIDDEN_EDITCOMPONENT_VIEW    40213
#define ID_HIDDEN_EDITCOMPONENT_ANIMATE 40214
#define ID_HIDDEN_EDITCOMPONENT_COLORS  40215
#define ID_HIDDEN_EDITCOMPONENT_SURFACES 40216
#define ID_HIDDEN_EDITCOMPONENT_CONTOURS 40217
#define ID_HIDDEN_EDITCOMPONENT_FUNCTIONS 40218
#define ID_HIDDEN_EDITCOMPONENT_PANELS  40219
#define ID_HIDDEN_EDITCOMPONENT_DESCRIPTION 40220
#define ID_HIDDEN_EDITCOMPONENT_TEXTFILE 40221
#define ID_CONNECTION_CONNECT           40222
#define ID_HIDDEN_DOMAGIC               40229
#define ID_UTILS_SNAPICON               40231
#define ID_TOOLS_RASBROWSER             40232
#define ID_SIZE_DEFAULTSIZE             40250
#define ID_SIZE_DOUBLESIZE              40251
#define ID_SIZE_KEEPASPECT              40252
#define ID_TOOLS_SNAPICON               40255
#define ID_UTILS_SNAPICONCLOSING        40256
#define ID_OBJECT_NEW                   40257
#define ID_OBJECT_LOAD                  40258
#define ID_OBJECT_SAVE                  40259
#define ID_OBJECT_MAKE_EXTENSION        40260
#define ID_OBJECT_POSITIONINBROWSER     40261
#define ID_OBJECT_SHOWLABTABLE          40263
#define ID_OBJECT_CLOSE                 40264
#define ID_OBJECT_EXIT                  40265
#define ID_SIMULATION_NEWMODEL          40269
#define ID_SIMULATION_CONTINUOUSMODELING 40270
#define ID_SIMULATION_STOP              40271
#define ID_SIMULATION_GO                40272
#define ID_SIMULATION_NEWLSYSTEM        40273
#define ID_SIMULATION_NEWHOMOMORPHISM   40274
#define ID_SIMULATION_NEWVIEW           40275
#define ID_SIMULATION_NEWPROJECTION     40276
#define ID_SIMULATION_NEWRENDER         40277
#define ID_SIMULATION_NEWANIMATE        40278
#define ID_SIMULATION_RERUN             40279
#define ID_PREFERENCES_EDIT_GENERAL     40280
#define ID_PREFERENCES_EDIT_CURRENTEDITOR 40281
#define ID_PREFERENCES_LOADFROM         40282
#define ID_PREFERENCES_SAVETO           40283
#define ID_TOOLS_BROWSER_OPENLOCAL      40284
#define ID_TOOLS_BROWSER_OPENREMOTE     40285
#define ID_WINDOW_TILEHORIZONTALLY      40286
#define ID_WINDOW_TILEVERTICALLY        40287
#define ID_WINDOW_CLOSEALL              40288
#define ID_HELP_LSTUDIOMANUAL           40289
#define ID_HELP_CPFGMANUALS_USERSMANUAL 40290
#define ID_HELP_CPFGMANUALS_ENVIRONMENTAL 40291
#define ID_HELP_CPFGMANUALS_GRAPHICSEXT 40292
#define ID_HELP_ABOUT                   40293
#define ID_COLORMAPWND_INTERPOLATE      40294
#define ID_COLORMAPWND_INVERSE          40295
#define ID_COLORMAPWND_REVERSE          40296
#define ID_MATERIALPREVIEW_APPLY        40297
#define ID_MATERIALPREVIEW_RETRIEVE     40298
#define ID_BB_XY                        40299
#define ID_BB_YZ                        40300
#define ID_BB_ZX                        40301
#define ID_BB_ORIENTATION               40302
#define ID_CONTOURPREV_APPLY            40303
#define ID_CONTOURPREV_RETRIEVE         40304
#define ID_CONTOURPREV_ADDASNEW         40305
#define ID_CONTOURPREV_FIT              40306
#define ID_SURFACEPREV_APPLY            40307
#define ID_SURFACEPREV_RETRIEVE         40308
#define ID_SURFACEPREV_ADDASNEW         40309
#define ID_SURFACEPREV_RESETROTATION    40310
#define ID_SURFACEPREV_LOCKXY           40311
#define ID_SURFACEPREV_DISPLAY_MESH     40312
#define ID_SURFACEPREV_DISPLAY_WIREFRAME 40313
#define ID_SURFACEPREV_DISPLAY_DENSEWIREFRAME 40314
#define ID_SURFACEPREV_DISPLAY_VERYDENSEWIREFRAME 40315
#define ID_SURFACEPREV_DISPLAY_SHADED   40316
#define ID_SURFACEPREV_DISPLAY_CONTROLPOINTS 40317
#define ID_SURFACEPREV_DISPLAY_CONTROLPOINTSNMBRS 40318
#define ID_SURFACEPREV_KEEPSYMMETRIC    40319
#define ID_CONTOURGALLERY_NEW           40320
#define ID_CONTOURGALLERY_DELETE        40321
#define ID_CONTOURGALLERY_COPY          40323
#define ID_SURFACEGALLERY_NEW           40324
#define ID_WINDOWS_CASCADE              40324
#define ID_SURFACEGALLERY_DELETE        40325
#define ID_OBJECT_CREATEDEMOFILE        40325
#define ID_SURFACEGALLERY_COPY          40326
#define ID_FROMCPFG_EXITING             40327
#define ID_CONTOUREPREVNEW_APPLY        40328
#define ID_CONTOUREPREVNEW_RETRIEVE     40329
#define ID_CONTOUREPREVNEW_ADD          40330
#define ID_CONTOUREPREVNEW_XYPLANE      40331
#define ID_CONTOUREPREVNEW_YZPLANE      40332
#define ID_CONTOUREPREVNEW_ZXPLANE      40333
#define ID_CONTOUREPREVNEW_ACTIVEPREV   40334
#define ID_NEWSURFVIEW_VIEWALL          40335
#define ID_NEWSURFVIEW_DEFAULTVIEW      40336
#define ID_FUNCTIONGALLERY_NEW          40337
#define ID_FUNCTIONGALLERY_DELETE       40338
#define ID_FUNCTIONGALLERY_COPY         40339
#define ID_FUNCTIONPREVIEW_APPLY        40340
#define ID_FUNCTIONPREVIEW_RETRIEVE     40341
#define ID_FUNCTIONPREVIEW_ADD          40342
#define ID_FUNCTIONPREVIEW_FIT          40343
#define ID_MATERIALGALLERY_COPY         40344
#define ID_MATERIALGALLERY_PASTE        40345
#define ID_MATERIALGALLERY_INTERPOLATE  40346
#define ID_CURVEPREVIEW_APPLY           40347
#define ID_CURVEPREVIEW_RETRIEVE        40348
#define ID_CURVEPREVIEW_ADDASNEW        40349
#define ID_CURVEPREVIEW_FITTOWINDOW     40350
#define ID_CURVEGALLERY_NEW             40351
#define ID_CURVEGALLERY_DELETE          40352
#define ID_HIDDEN_TESTINTERPRETER       40353
#define ID_HIDDEN_TESTNEWSURFACE        40354
#define ID_SIMULATION_BUILD             40355

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        361
#define _APS_NEXT_COMMAND_VALUE         40326
#define _APS_NEXT_CONTROL_VALUE         2558
#define _APS_NEXT_SYMED_VALUE           301
#endif
#endif
