#define IDC_VLABEL                      1000
#define IDC_SLABEL                      1001
#define IDC_REDSLIDER                   1002
#define IDC_GREENSLIDER                 1003
#define IDC_BLUESLIDER                  1004
#define IDC_HLABEL                      1005
#define IDC_BLABEL                      1006
#define IDC_GLABEL                      1007
#define IDC_RLABEL                      1008
#define IDC_UNDO                        1009
#define IDC_RED                         1020
#define IDC_GREEN                       1021
#define IDC_BLUE                        1022
#define IDC_HUE                         1096
#define IDC_SATURATION                  1097
#define IDC_HUECIRCLE                   1132
#define IDC_VALUE                       1171
#define IDC_APPLY                       1223
#define IDC_HUESLIDER                   1230
#define IDC_SATURATIONSLIDER            1231
#define IDC_VALUESLIDER                 1232
